### ISSUE TITLE
Створити ескіз головної сторінки

### ISSUE THREAD

**Issue by workingchuckis** [workingchuckis/album#3]
Требования:

1. Лого та Заголовок: Додати логотип школи/класу та заголовок, що привертає увагу, що описує захід.
2. Галерея: Передбачити блок відображення фотографій з попередніх випускних вечорів.
3. Контактна інформація
4. Дизайн та Верстка: Дотриматися базових принципів дизайну та зручності використання, забезпечити чіткість та зрозумілість інтерфейсу.

Додаткові зауваження:

Ескіз має бути представлений у форматі, зрозумілому для обговорення (наприклад, креслення на папері, цифровий макет).
Переважно враховувати поради та пропозиції щодо покращення від команди.
Уважно стежити за одноманітністю стилю та кольорової гами.

**Comment by chuckis** [comment]
@imann21D1  [Посилання](https://docs.github.com/ru/repositories/working-with-files/managing-files/adding-a-file-to-a-repository) на документацію щодо додавання файлу у СВІЙ (свій форк) репозиторію.

**Comment by chuckis** [comment]
Повторяем все о языке разметки [HTML](https://w3schoolsua.github.io/html/index.html#gsc.tab=0). Там есть упражнения. Кто прочитал, отреагируйте на этот комментарий

**Comment by chuckis** [comment]
@imann21D1 , @burickim , проверка связи
